"""add approved_disapproved_by and disapproval reason to achievement model

Revision ID: a7f56627048a
Revises: 7c71fc44406c
Create Date: 2022-11-11 18:34:47.689128

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7f56627048a"
down_revision = "7c71fc44406c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("disapproval_reason", sa.String(length=4096), nullable=True)
        )
        batch_op.add_column(
            sa.Column("approved_disapproved_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_achievement_approved_disapproved_by_user"),
            "user",
            ["approved_disapproved_by"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_achievement_approved_disapproved_by_user"),
            type_="foreignkey",
        )
        batch_op.drop_column("approved_disapproved_by")
        batch_op.drop_column("disapproval_reason")

    # ### end Alembic commands ###
