"""create basis and criteria models

Revision ID: cb1c9a831941
Revises: 230d1cfe0765
Create Date: 2022-05-10 22:13:10.920260

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb1c9a831941"
down_revision = "230d1cfe0765"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basis",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_basis")),
    )
    with op.batch_alter_table("basis", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_basis_id"), ["id"], unique=False)

    op.create_table(
        "criteria",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("basis_id", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["basis_id"], ["basis.id"], name=op.f("fk_criteria_basis_id_basis")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_criteria")),
    )
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_criteria_basis_id"), ["basis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_criteria_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_criteria_id"))
        batch_op.drop_index(batch_op.f("ix_criteria_basis_id"))

    op.drop_table("criteria")
    with op.batch_alter_table("basis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_basis_id"))

    op.drop_table("basis")
    # ### end Alembic commands ###
