"""Make user_id in balance nullable

Revision ID: 037558a92540
Revises: 8f5feadd711f
Create Date: 2022-05-02 12:13:18.119969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037558a92540'
down_revision = '8f5feadd711f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
