"""add image columns to gift and user

Revision ID: 230d1cfe0765
Revises: c3d01a6e11ad
Create Date: 2022-05-10 18:48:53.398622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230d1cfe0765'
down_revision = 'c3d01a6e11ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
