"""update user model for sso auth (remove password column)

Revision ID: 736a5f7f2b1b
Revises: 7c71fc44406c
Create Date: 2022-11-01 14:08:49.533205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736a5f7f2b1b'
down_revision = '7c71fc44406c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
