"""make is_user_achievable not nullable

Revision ID: 7c71fc44406c
Revises: e5d3e7a54e06
Create Date: 2022-09-26 20:37:18.136603

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c71fc44406c"
down_revision = "e5d3e7a54e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE criteria SET is_user_achievable = false")
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.alter_column(
            "is_user_achievable", existing_type=sa.BOOLEAN(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.alter_column(
            "is_user_achievable", existing_type=sa.BOOLEAN(), nullable=True
        )

    # ### end Alembic commands ###
