"""add creation_date for order

Revision ID: a3de2fa9f9fa
Revises: b85a99dd9565
Create Date: 2022-09-08 21:36:53.211898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3de2fa9f9fa'
down_revision = 'b85a99dd9565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
