"""add edit_date column to achievement

Revision ID: c08132e6a185
Revises: a7f56627048a
Create Date: 2022-11-11 19:07:12.353431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08132e6a185'
down_revision = 'a7f56627048a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('edit_date')

    # ### end Alembic commands ###
