"""add status column to order and remive is_issued and returned columns

Revision ID: d3b23c646b74
Revises: 966e99cd2f52
Create Date: 2022-12-04 19:18:09.837104

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

from db.models.order import OrderStatusEnum

# revision identifiers, used by Alembic.
revision = "d3b23c646b74"
down_revision = "966e99cd2f52"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    Session(bind=conn)
    orderstatus_enum = postgresql.ENUM(
        *[i.value for i in OrderStatusEnum], name="orderstatus", create_type=False
    )
    orderstatus_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", orderstatus_enum, nullable=False))
        batch_op.drop_column("is_returned")
        batch_op.drop_column("is_issued")

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.alter_column("status", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_issued", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_returned", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
    # ### end Alembic commands ###
