"""add is_user_achievable field for Criteria

Revision ID: e5d3e7a54e06
Revises: f8bda89b7e16
Create Date: 2022-09-26 19:42:49.593842

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5d3e7a54e06"
down_revision = "f8bda89b7e16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_user_achievable", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.drop_column("is_user_achievable")

    # ### end Alembic commands ###
