"""add is_teacher field for user

Revision ID: f8bda89b7e16
Revises: a3de2fa9f9fa
Create Date: 2022-09-08 22:29:48.583752

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8bda89b7e16"
down_revision = "a3de2fa9f9fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_teacher", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_teacher")

    # ### end Alembic commands ###
